config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # mostrar todas as tarefas para o usuario
  get 'tasks', to: 'tasks#index'

  #mostrar formulario de criacao de nova task
  get 'tasks/new', to: 'tasks#new', as: :new

  #mostrar uma tarefa especifica para o usuario
  get 'tasks/:id', to: 'tasks#show', as: :task

  #salvar nova task
  post 'tasks', to: 'tasks#create'

  #editar nova task = pagina de edicao
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  #atualizar task editada
  patch 'tasks/:id', to: 'tasks#update'

  #deletar uma task
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy

    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/06723c66f0.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details%>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed%>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<div>
  <ul>
    <% @tasks.each do |task| %>

        <% if task.completed %>
          <li>
            <i class="fas fa-check-circle"></i>
            <%= link_to task.title, task_path(task)%>
            <%= link_to delete_task_path(task), class: "btn btn-default", method: :delete,
                  data: { confirm: "Are you sure?" }  do %>
            <i class="far fa-trash-alt"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <i class="far fa-square"></i>
            <%= link_to task.title, task_path(task)%>
            <%= link_to delete_task_path(task), class: "btn btn-default", method: :delete,
                  data: { confirm: "Are you sure?" }  do %>
            <i class="far fa-trash-alt"></i>
            <% end %>
          </li>
        <% end %>


    <% end %>
   </ul>
  </div>

  <%= link_to "New task", new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>
<p><strong>Details</strong>: <%= @task.details %></p>
<p><strong>Completed</strong>: <%= @task.completed %></p>
<%= link_to "Update task", edit_task_path(@task) %>
<%= link_to 'Back to list of tasks', tasks_path %>